// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgrmzxgfnvjfukvotofi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRncm16eGdmbnZqZnVrdm90b2ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMTM1NDUsImV4cCI6MjA1MjU4OTU0NX0.-Dk8xwziOI7jsWJMYnJQ4joQ8bqFXbT46OhCP0wEB5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);